### ISSUE TITLE
TODO for 0.1

### ISSUE THREAD

**Issue by shantanugoel** [shantanugoel/email-actions#1]
- [x] Add error handling in time instead of having to ctrl+c to see them
- [x] Move configuration from config.py to a proper config file
- [x] Add cli arguments for hostname, port and config file location
- [x] Allow to specify action (internal plugin or external command) in config file
- [x] Add better and configurable logging
- [x] Enhance plugin infra
- [x] Run the action asynch
- [x] Add exec plugin
- [x] Add email plugin
- [x] Add README
- [x] Make package
